name: documentation
on:
  pull_request:
    branches: [ feature/docusaurus ]
  push:
    branches: [ feature/docusaurus ]
jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          cd eigr_io
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
#      - uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: git
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: main
        run: |
          git config --global user.email "marcellanz@n-1.ch"
          git config --global user.name "marcellanz"
          cd eigr_io
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy